version: '2'
services:
  jm-app:
    image: app
    ports:
    - "8888:8080"
    depends_on:
    - jm-postgres
  jm-postgres:
    image: postgres:11.7
    ports:
     - "5431:5432"
    environment:
      POSTGRES_PASSWORD: '12345'
      POSTGRES_USER: postgres
      POSTGRES_DB: app